version: "3"

services:
  web:
    build: .
    volumes:
      - .:/app
      - app:/home/app
      - "~/.gitconfig:/home/app/.gitconfig"
    working_dir: /app
    environment:
      MIX_BUILD_ROOT: /home/app/_build
      MIX_DEPS_PATH: /home/app/deps
  redis:
    image: public.ecr.aws/bitnami/redis:5.0
    ports:
      - "6379:6379"
    hostname: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  app:
